# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 2c8344f8629b57bb9ae59a1d3892693dfce50a36

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: boinq@localhost

spring:
    R:
        port: 6311
        host: localhost

    fuseki:
        port: 8899
        jettyconfigfile: fuseki/jetty-fuseki.xml
        workpath: fuseki/run/

    triplestore:
        endpoint: 
            update: http://localhost:8080/fuseki/boinq/update
            sparql: http://localhost:8080/fuseki/boinq/sparql
            meta: http://localhost:8080/fuseki/boinq/update
            external: http://localhost:8888/fuseki/sparql
 #           update: http://localhost:9999/bigdata/namespace/boinq/update
 #           sparql: http://localhost:9999/bigdata/namespace/boinq/sparql
 #           meta: http://localhost:9999/bigdata/namespace/boinq/update
 #           external: http://localhost:8888/fuseki/sparql

        metagraph: http://www.boinq.org/iri/graph/meta/
        localdatasource: http://www.boinq.org/iri/localdatasource
        graphbase: http://www.boinq.org/iri/graph/local#
            
    triplegen:
        baseIRI: http://www.boinq.org/iri/
        baseIRIlink: http://localhost:8888/iri/
# baseIRIlink is used by ELDA to translate the links for local development

    propertyplaceholder:
        templates:
         - 
           template: config/config_template.ttl
           target: src/main/webapp/elda/config.ttl

swagger:
    title: boinq API
    description: boinq !
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
