server:
    port: 10344
    address: localhost


# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 2c8344f8629b57bb9ae59a1d3892693dfce50a36

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

liquibase:
    context: test

spring:

    R:
        port: 6311
        host: localhost

    triplestore:
        endpoint: 
#            update: http://localhost:8899/DYNAMIC/update
#            sparql: http://localhost:8899/DYNAMIC/sparql
#           meta: http://localhost:8899/DYNAMIC/update
#            external: http://localhost:8888/fuseki/sparql
#          update: http://localhost:9999/bigdata/namespace/test1/sparql  
#          sparql: http://localhost:9999/bigdata/namespace/test1/sparql
#          meta: http://localhost:9999/bigdata/namespace/sparql
#          external: http://localhost:9999/bigdata/sparql
        
           update: http://localhost:8080/fuseki/boinq/update
           static: http://localhost:8080/fuseki/boinq_static/update
           sparql: http://localhost:8080/fuseki/boinq/sparql
           meta: http://localhost:8080/fuseki/boinq/update
           external: http://localhost:8888/fuseki/sparql
           
        metagraph: http://www.boinq.org/iri/graph/meta/
        localdatasource: http://www.boinq.org/iri/localdatasource
        graphbase: http://www.boinq.org/iri/graph/local#
            
    triplegen:
        baseIRI: http://www.boinq.org/iri/
        baseIRIlink: http://localhost:8888/iri/
# baseIRIlink is used by ELDA to translate the links for local development

    propertyplaceholder:
        templates:
         - 
           template: config/config_template.ttl
           target: src/main/webapp/elda/config.ttl


    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:boinq;DB_CLOSE_DELAY=-1
        databaseName:
        serverName:
        username:
        password:

    jpa:
        database-platform: com.genohm.boinq.domain.util.FixedH2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false

metrics:
    jmx.enabled: false

swagger:
    apiDocsLocation: http://localhost:8080
    title: jhipster API
    version: 0.0.1
    description: jhipster applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html